### ISSUE TITLE
Close an Issue for a particular Check

### ISSUE THREAD

**Issue by suhasgumma** [lucasbento/auto-close-issues#16]
Right now, only issues which do not match the template are being closed. Could you add functionality to "Close the issue" for a particular condition the user needs?

Example Scenario:
If my issue has a particular label, it has to close automatically.

my workflow would be like this:
```
on:
  issues:
    types: [opened, labeled]

jobs:
  auto_close_issues:
    if: github.event.label.name == 'typo'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Automatically close typo issues
        uses: lucasbento/auto-close-issues@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-close-message: "@${issue.user.login}: Hello! :wave:\n\nThis issue is being automatically closed, Please open a PR with a relevant fix."
```
